kisa=input('Kısa Kenar : ')
uzun=input('Uzun Kenar : ')
alan=int(kisa)*int(uzun)
cevre=2*(int(kisa)+int(uzun))
print("Dikdrötgenin Alanı : {0}".format(alan))
print("Dikdörtgenin Çevresi : {0}".format(cevre))